// SPDX-FileCopyrightText: Copyright The arm-sysregs Contributors.
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Access to Arm CPU system registers.

// This file is generated, do not edit manually.

// `unused_imports` is allowed because it is possible that not all of these macros are used in the
// generated output.
#[allow(unused_imports)]
use arm_sysregs_common::{read_sysreg, read_write_sysreg, write_sysreg};

read_write_sysreg!(actlr: (p15, 0, c0, c1, 1), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(actlr2: (p15, 0, c0, c1, 3), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(adfsr: (p15, 0, c1, c5, 0), u32, safe_read, crate::fake::SYSREGS);
read_sysreg!(aidr: (p15, 1, c0, c0, 7), u32, safe, crate::fake::SYSREGS);
read_write_sysreg!(aifsr: (p15, 0, c1, c5, 1), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amair0: (p15, 0, c3, c10, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amair1: (p15, 0, c3, c10, 1), u32, safe_read, crate::fake::SYSREGS);
read_sysreg!(amcfgr: (p15, 0, c2, c13, 1), u32: crate::registers::Amcfgr, safe, crate::fake::SYSREGS);
read_sysreg!(amcgcr: (p15, 0, c2, c13, 2), u32: crate::registers::Amcgcr, safe, crate::fake::SYSREGS);
read_write_sysreg!(amcntenclr0: (p15, 0, c2, c13, 4), u32: crate::registers::Amcntenclr0, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amcntenclr1: (p15, 0, c3, c13, 0), u32: crate::registers::Amcntenclr1, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amcntenset0: (p15, 0, c2, c13, 5), u32: crate::registers::Amcntenset0, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amcntenset1: (p15, 0, c3, c13, 1), u32: crate::registers::Amcntenset1, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amcr: (p15, 0, c2, c13, 0), u32: crate::registers::Amcr, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amevcntr00: (p15, 0, c0), u64: crate::registers::Amevcntr00, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amevcntr01: (p15, 1, c0), u64: crate::registers::Amevcntr01, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amevcntr02: (p15, 2, c0), u64: crate::registers::Amevcntr02, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(amevcntr03: (p15, 3, c0), u64: crate::registers::Amevcntr03, safe_read, safe_write, crate::fake::SYSREGS);
read_sysreg!(amevtyper00: (p15, 0, c6, c13, 0), u32: crate::registers::Amevtyper00, safe, crate::fake::SYSREGS);
read_sysreg!(amevtyper01: (p15, 0, c6, c13, 1), u32: crate::registers::Amevtyper01, safe, crate::fake::SYSREGS);
read_sysreg!(amevtyper02: (p15, 0, c6, c13, 2), u32: crate::registers::Amevtyper02, safe, crate::fake::SYSREGS);
read_sysreg!(amevtyper03: (p15, 0, c6, c13, 3), u32: crate::registers::Amevtyper03, safe, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper10: (p15, 0, c14, c13, 0), u32: crate::registers::Amevtyper10, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper11: (p15, 0, c14, c13, 1), u32: crate::registers::Amevtyper11, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper110: (p15, 0, c15, c13, 2), u32: crate::registers::Amevtyper110, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper111: (p15, 0, c15, c13, 3), u32: crate::registers::Amevtyper111, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper112: (p15, 0, c15, c13, 4), u32: crate::registers::Amevtyper112, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper113: (p15, 0, c15, c13, 5), u32: crate::registers::Amevtyper113, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper114: (p15, 0, c15, c13, 6), u32: crate::registers::Amevtyper114, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper115: (p15, 0, c15, c13, 7), u32: crate::registers::Amevtyper115, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper12: (p15, 0, c14, c13, 2), u32: crate::registers::Amevtyper12, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper13: (p15, 0, c14, c13, 3), u32: crate::registers::Amevtyper13, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper14: (p15, 0, c14, c13, 4), u32: crate::registers::Amevtyper14, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper15: (p15, 0, c14, c13, 5), u32: crate::registers::Amevtyper15, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper16: (p15, 0, c14, c13, 6), u32: crate::registers::Amevtyper16, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper17: (p15, 0, c14, c13, 7), u32: crate::registers::Amevtyper17, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper18: (p15, 0, c15, c13, 0), u32: crate::registers::Amevtyper18, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amevtyper19: (p15, 0, c15, c13, 1), u32: crate::registers::Amevtyper19, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(amuserenr: (p15, 0, c2, c13, 3), u32: crate::registers::Amuserenr, safe_read, safe_write, crate::fake::SYSREGS);
read_sysreg!(ccsidr: (p15, 1, c0, c0, 0), u32: crate::registers::Ccsidr, safe, crate::fake::SYSREGS);
read_sysreg!(ccsidr2: (p15, 1, c0, c0, 2), u32: crate::registers::Ccsidr2, safe, crate::fake::SYSREGS);
read_sysreg!(clidr: (p15, 1, c0, c0, 1), u32: crate::registers::Clidr, safe, crate::fake::SYSREGS);
read_write_sysreg!(cntfrq: (p15, 0, c0, c14, 0), u32: crate::registers::Cntfrq, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthctl: (p15, 4, c1, c14, 0), u32: crate::registers::Cnthctl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthps_ctl: (p15, 0, c2, c14, 1), u32: crate::registers::CnthpsCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthps_cval: (p15, 2, c14), u64: crate::registers::CnthpsCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthps_tval: (p15, 0, c2, c14, 0), u32: crate::registers::CnthpsTval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthp_ctl: (p15, 0, c2, c14, 1), u32: crate::registers::CnthpCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthp_cval: (p15, 2, c14), u64: crate::registers::CnthpCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthp_tval: (p15, 0, c2, c14, 0), u32: crate::registers::CnthpTval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthvs_ctl: (p15, 0, c3, c14, 1), u32: crate::registers::CnthvsCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthvs_cval: (p15, 3, c14), u64: crate::registers::CnthvsCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthvs_tval: (p15, 0, c3, c14, 0), u32: crate::registers::CnthvsTval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthv_ctl: (p15, 0, c3, c14, 1), u32: crate::registers::CnthvCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthv_cval: (p15, 3, c14), u64: crate::registers::CnthvCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cnthv_tval: (p15, 0, c3, c14, 0), u32: crate::registers::CnthvTval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntkctl: (p15, 0, c1, c14, 0), u32: crate::registers::Cntkctl, safe_read, crate::fake::SYSREGS);
read_sysreg!(cntpct: (p15, 0, c14), u64: crate::registers::Cntpct, safe, crate::fake::SYSREGS);
read_sysreg!(cntpctss: (p15, 8, c14), u64: crate::registers::Cntpctss, safe, crate::fake::SYSREGS);
read_write_sysreg!(cntp_ctl: (p15, 0, c2, c14, 1), u32: crate::registers::CntpCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntp_cval: (p15, 2, c14), u64: crate::registers::CntpCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntp_tval: (p15, 0, c2, c14, 0), u32: crate::registers::CntpTval, safe_read, crate::fake::SYSREGS);
read_sysreg!(cntvct: (p15, 1, c14), u64: crate::registers::Cntvct, safe, crate::fake::SYSREGS);
read_sysreg!(cntvctss: (p15, 9, c14), u64: crate::registers::Cntvctss, safe, crate::fake::SYSREGS);
read_write_sysreg!(cntvoff: (p15, 4, c14), u64: crate::registers::Cntvoff, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntv_ctl: (p15, 0, c3, c14, 1), u32: crate::registers::CntvCtl, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntv_cval: (p15, 3, c14), u64: crate::registers::CntvCval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cntv_tval: (p15, 0, c3, c14, 0), u32: crate::registers::CntvTval, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(contextidr: (p15, 0, c0, c13, 1), u32: crate::registers::Contextidr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(cpacr: (p15, 0, c0, c1, 2), u32: crate::registers::Cpacr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(csselr: (p15, 2, c0, c0, 0), u32: crate::registers::Csselr, safe_read, crate::fake::SYSREGS);
read_sysreg!(ctr: (p15, 0, c0, c0, 1), u32: crate::registers::Ctr, safe, crate::fake::SYSREGS);
read_write_sysreg!(dacr: (p15, 0, c0, c3, 0), u32: crate::registers::Dacr, safe_read, crate::fake::SYSREGS);
read_sysreg!(dbgauthstatus: (p14, 0, c14, c7, 6), u32: crate::registers::Dbgauthstatus, safe, crate::fake::SYSREGS);
read_write_sysreg!(dbgclaimclr: (p14, 0, c9, c7, 6), u32: crate::registers::Dbgclaimclr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dbgclaimset: (p14, 0, c8, c7, 6), u32: crate::registers::Dbgclaimset, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dbgdccint: (p14, 0, c2, c0, 0), u32: crate::registers::Dbgdccint, safe_read, crate::fake::SYSREGS);
read_sysreg!(dbgdevid: (p14, 0, c2, c7, 7), u32: crate::registers::Dbgdevid, safe, crate::fake::SYSREGS);
read_sysreg!(dbgdevid1: (p14, 0, c1, c7, 7), u32: crate::registers::Dbgdevid1, safe, crate::fake::SYSREGS);
read_sysreg!(dbgdevid2: (p14, 0, c0, c7, 7), u32, safe, crate::fake::SYSREGS);
read_sysreg!(dbgdidr: (p14, 0, c0, c0, 0), u32: crate::registers::Dbgdidr, safe, crate::fake::SYSREGS);
read_sysreg!(dbgdrar: (p14, 0, c1), u64: crate::registers::Dbgdrar, safe, crate::fake::SYSREGS);
read_sysreg!(dbgdsar: (p14, 0, c2), u64, safe, crate::fake::SYSREGS);
read_write_sysreg!(dbgdscrext: (p14, 0, c2, c0, 2), u32: crate::registers::Dbgdscrext, safe_read, crate::fake::SYSREGS);
read_sysreg!(dbgdscrint: (p14, 0, c1, c0, 0), u32: crate::registers::Dbgdscrint, safe, crate::fake::SYSREGS);
read_write_sysreg!(dbgdtrrxext: (p14, 0, c0, c0, 2), u32: crate::registers::Dbgdtrrxext, safe_read, crate::fake::SYSREGS);
read_sysreg!(dbgdtrrxint: (p14, 0, c5, c0, 0), u32: crate::registers::Dbgdtrrxint, safe, crate::fake::SYSREGS);
read_write_sysreg!(dbgdtrtxext: (p14, 0, c3, c0, 2), u32: crate::registers::Dbgdtrtxext, safe_read, crate::fake::SYSREGS);
write_sysreg!(dbgdtrtxint: (p14, 0, c5, c0, 0), u32: crate::registers::Dbgdtrtxint, crate::fake::SYSREGS);
read_write_sysreg!(dbgosdlr: (p14, 0, c3, c1, 4), u32: crate::registers::Dbgosdlr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dbgoseccr: (p14, 0, c6, c0, 2), u32: crate::registers::Dbgoseccr, safe_read, crate::fake::SYSREGS);
write_sysreg!(dbgoslar: (p14, 0, c0, c1, 4), u32: crate::registers::Dbgoslar, crate::fake::SYSREGS);
read_sysreg!(dbgoslsr: (p14, 0, c1, c1, 4), u32: crate::registers::Dbgoslsr, safe, crate::fake::SYSREGS);
read_write_sysreg!(dbgprcr: (p14, 0, c4, c1, 4), u32: crate::registers::Dbgprcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dbgvcr: (p14, 0, c7, c0, 0), u32: crate::registers::Dbgvcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dbgwfar: (p14, 0, c6, c0, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dfar: (p15, 0, c0, c6, 0), u32: crate::registers::Dfar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dfsr: (p15, 0, c0, c5, 0), u32: crate::registers::Dfsr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(disr: (p15, 0, c1, c12, 1), u32: crate::registers::Disr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dlr: (p15, 3, c5, c4, 1), u32: crate::registers::Dlr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dspsr: (p15, 3, c5, c4, 0), u32: crate::registers::Dspsr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(dspsr2: (p15, 3, c5, c4, 2), u32: crate::registers::Dspsr2, safe_read, crate::fake::SYSREGS);
#[cfg(feature = "el2")]
read_write_sysreg!(elr_hyp, u32: crate::registers::ElrHyp, safe_read, crate::fake::SYSREGS);
read_sysreg!(erridr: (p15, 0, c3, c5, 0), u32: crate::registers::Erridr, safe, crate::fake::SYSREGS);
read_write_sysreg!(errselr: (p15, 0, c3, c5, 1), u32: crate::registers::Errselr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxaddr: (p15, 0, c4, c5, 3), u32: crate::registers::Erxaddr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxaddr2: (p15, 0, c4, c5, 7), u32: crate::registers::Erxaddr2, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxctlr: (p15, 0, c4, c5, 1), u32: crate::registers::Erxctlr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxctlr2: (p15, 0, c4, c5, 5), u32: crate::registers::Erxctlr2, safe_read, crate::fake::SYSREGS);
read_sysreg!(erxfr: (p15, 0, c4, c5, 0), u32: crate::registers::Erxfr, safe, crate::fake::SYSREGS);
read_sysreg!(erxfr2: (p15, 0, c4, c5, 4), u32: crate::registers::Erxfr2, safe, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc0: (p15, 0, c5, c5, 0), u32: crate::registers::Erxmisc0, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc1: (p15, 0, c5, c5, 1), u32: crate::registers::Erxmisc1, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc2: (p15, 0, c5, c5, 4), u32: crate::registers::Erxmisc2, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc3: (p15, 0, c5, c5, 5), u32: crate::registers::Erxmisc3, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc4: (p15, 0, c5, c5, 2), u32: crate::registers::Erxmisc4, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc5: (p15, 0, c5, c5, 3), u32: crate::registers::Erxmisc5, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc6: (p15, 0, c5, c5, 6), u32: crate::registers::Erxmisc6, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxmisc7: (p15, 0, c5, c5, 7), u32: crate::registers::Erxmisc7, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(erxstatus: (p15, 0, c4, c5, 2), u32: crate::registers::Erxstatus, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(fcseidr: (p15, 0, c0, c13, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hacr: (p15, 4, c1, c1, 7), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hactlr: (p15, 4, c0, c1, 1), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hactlr2: (p15, 4, c0, c1, 3), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hadfsr: (p15, 4, c1, c5, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(haifsr: (p15, 4, c1, c5, 1), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hamair0: (p15, 4, c3, c10, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hamair1: (p15, 4, c3, c10, 1), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hcptr: (p15, 4, c1, c1, 2), u32: crate::registers::Hcptr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hcr: (p15, 4, c1, c1, 0), u32: crate::registers::Hcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hcr2: (p15, 4, c1, c1, 4), u32: crate::registers::Hcr2, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hdcr: (p15, 4, c1, c1, 1), u32: crate::registers::Hdcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hdfar: (p15, 4, c0, c6, 0), u32: crate::registers::Hdfar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hifar: (p15, 4, c0, c6, 2), u32: crate::registers::Hifar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hmair0: (p15, 4, c2, c10, 0), u32: crate::registers::Hmair0, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hmair1: (p15, 4, c2, c10, 1), u32: crate::registers::Hmair1, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hpfar: (p15, 4, c0, c6, 4), u32: crate::registers::Hpfar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hrmr: (p15, 4, c0, c12, 2), u32: crate::registers::Hrmr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hsctlr: (p15, 4, c0, c1, 0), u32: crate::registers::Hsctlr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hsr: (p15, 4, c2, c5, 0), u32: crate::registers::Hsr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hstr: (p15, 4, c1, c1, 3), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(htcr: (p15, 4, c0, c2, 2), u32: crate::registers::Htcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(htpidr: (p15, 4, c0, c13, 2), u32: crate::registers::Htpidr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(htrfcr: (p15, 4, c2, c1, 1), u32: crate::registers::Htrfcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(httbr: (p15, 4, c2), u64: crate::registers::Httbr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(hvbar: (p15, 4, c0, c12, 0), u32: crate::registers::Hvbar, safe_read, crate::fake::SYSREGS);
write_sysreg!(icc_asgi1r: (p15, 1, c12), u64: crate::registers::IccAsgi1r, safe, crate::fake::SYSREGS);
read_write_sysreg!(icc_bpr0: (p15, 0, c8, c12, 3), u32: crate::registers::IccBpr0, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_bpr1: (p15, 0, c12, c12, 3), u32: crate::registers::IccBpr1, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_ctlr: (p15, 0, c12, c12, 4), u32: crate::registers::IccCtlr, safe_read, safe_write, crate::fake::SYSREGS);
write_sysreg!(icc_dir: (p15, 0, c11, c12, 1), u32: crate::registers::IccDir, safe, crate::fake::SYSREGS);
write_sysreg!(icc_eoir0: (p15, 0, c8, c12, 1), u32: crate::registers::IccEoir0, safe, crate::fake::SYSREGS);
write_sysreg!(icc_eoir1: (p15, 0, c12, c12, 1), u32: crate::registers::IccEoir1, safe, crate::fake::SYSREGS);
read_sysreg!(icc_hppir0: (p15, 0, c8, c12, 2), u32: crate::registers::IccHppir0, safe, crate::fake::SYSREGS);
read_sysreg!(icc_hppir1: (p15, 0, c12, c12, 2), u32: crate::registers::IccHppir1, safe, crate::fake::SYSREGS);
read_write_sysreg!(icc_hsre: (p15, 4, c9, c12, 5), u32: crate::registers::IccHsre, safe_read, crate::fake::SYSREGS);
read_sysreg!(icc_iar0: (p15, 0, c8, c12, 0), u32: crate::registers::IccIar0, safe, crate::fake::SYSREGS);
read_sysreg!(icc_iar1: (p15, 0, c12, c12, 0), u32: crate::registers::IccIar1, safe, crate::fake::SYSREGS);
read_write_sysreg!(icc_igrpen0: (p15, 0, c12, c12, 6), u32: crate::registers::IccIgrpen0, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_igrpen1: (p15, 0, c12, c12, 7), u32: crate::registers::IccIgrpen1, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_mctlr: (p15, 6, c12, c12, 4), u32: crate::registers::IccMctlr, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_mgrpen1: (p15, 6, c12, c12, 7), u32: crate::registers::IccMgrpen1, safe_read, safe_write, crate::fake::SYSREGS);
read_write_sysreg!(icc_msre: (p15, 6, c12, c12, 5), u32: crate::registers::IccMsre, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(icc_pmr: (p15, 0, c6, c4, 0), u32: crate::registers::IccPmr, safe_read, safe_write, crate::fake::SYSREGS);
read_sysreg!(icc_rpr: (p15, 0, c11, c12, 3), u32: crate::registers::IccRpr, safe, crate::fake::SYSREGS);
write_sysreg!(icc_sgi0r: (p15, 2, c12), u64: crate::registers::IccSgi0r, safe, crate::fake::SYSREGS);
write_sysreg!(icc_sgi1r: (p15, 0, c12), u64: crate::registers::IccSgi1r, safe, crate::fake::SYSREGS);
read_write_sysreg!(icc_sre: (p15, 0, c12, c12, 5), u32: crate::registers::IccSre, safe_read, crate::fake::SYSREGS);
read_sysreg!(id_afr0: (p15, 0, c1, c0, 3), u32, safe, crate::fake::SYSREGS);
read_sysreg!(id_dfr0: (p15, 0, c1, c0, 2), u32: crate::registers::IdDfr0, safe, crate::fake::SYSREGS);
read_sysreg!(id_dfr1: (p15, 0, c3, c0, 5), u32: crate::registers::IdDfr1, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar0: (p15, 0, c2, c0, 0), u32: crate::registers::IdIsar0, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar1: (p15, 0, c2, c0, 1), u32: crate::registers::IdIsar1, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar2: (p15, 0, c2, c0, 2), u32: crate::registers::IdIsar2, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar3: (p15, 0, c2, c0, 3), u32: crate::registers::IdIsar3, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar4: (p15, 0, c2, c0, 4), u32: crate::registers::IdIsar4, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar5: (p15, 0, c2, c0, 5), u32: crate::registers::IdIsar5, safe, crate::fake::SYSREGS);
read_sysreg!(id_isar6: (p15, 0, c2, c0, 7), u32: crate::registers::IdIsar6, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr0: (p15, 0, c1, c0, 4), u32: crate::registers::IdMmfr0, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr1: (p15, 0, c1, c0, 5), u32: crate::registers::IdMmfr1, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr2: (p15, 0, c1, c0, 6), u32: crate::registers::IdMmfr2, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr3: (p15, 0, c1, c0, 7), u32: crate::registers::IdMmfr3, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr4: (p15, 0, c2, c0, 6), u32: crate::registers::IdMmfr4, safe, crate::fake::SYSREGS);
read_sysreg!(id_mmfr5: (p15, 0, c3, c0, 6), u32: crate::registers::IdMmfr5, safe, crate::fake::SYSREGS);
read_sysreg!(id_pfr0: (p15, 0, c1, c0, 0), u32: crate::registers::IdPfr0, safe, crate::fake::SYSREGS);
read_sysreg!(id_pfr1: (p15, 0, c1, c0, 1), u32: crate::registers::IdPfr1, safe, crate::fake::SYSREGS);
read_sysreg!(id_pfr2: (p15, 0, c3, c0, 4), u32: crate::registers::IdPfr2, safe, crate::fake::SYSREGS);
read_write_sysreg!(ifar: (p15, 0, c0, c6, 2), u32: crate::registers::Ifar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(ifsr: (p15, 0, c0, c5, 1), u32: crate::registers::Ifsr, safe_read, crate::fake::SYSREGS);
read_sysreg!(isr: (p15, 0, c1, c12, 0), u32: crate::registers::Isr, safe, crate::fake::SYSREGS);
read_sysreg!(jidr: (p14, 7, c0, c0, 0), u32, safe, crate::fake::SYSREGS);
read_write_sysreg!(jmcr: (p14, 7, c0, c2, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(joscr: (p14, 7, c0, c1, 0), u32, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(mair0: (p15, 0, c2, c10, 0), u32: crate::registers::Mair0, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(mair1: (p15, 0, c2, c10, 1), u32: crate::registers::Mair1, safe_read, crate::fake::SYSREGS);
read_sysreg!(midr: (p15, 0, c0, c0, 0), u32: crate::registers::Midr, safe, crate::fake::SYSREGS);
read_sysreg!(mpidr: (p15, 0, c0, c0, 5), u32: crate::registers::Mpidr, safe, crate::fake::SYSREGS);
read_write_sysreg!(mvbar: (p15, 0, c0, c12, 1), u32: crate::registers::Mvbar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(nmrr: (p15, 0, c2, c10, 1), u32: crate::registers::Nmrr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(nsacr: (p15, 0, c1, c1, 2), u32: crate::registers::Nsacr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(par: (p15, 0, c7), u64: crate::registers::Par, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmccfiltr: (p15, 0, c15, c14, 7), u32: crate::registers::Pmccfiltr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmccntr: (p15, 0, c9), u64: crate::registers::Pmccntr, safe_read, crate::fake::SYSREGS);
read_sysreg!(pmceid0: (p15, 0, c12, c9, 6), u32: crate::registers::Pmceid0, safe, crate::fake::SYSREGS);
read_sysreg!(pmceid1: (p15, 0, c12, c9, 7), u32: crate::registers::Pmceid1, safe, crate::fake::SYSREGS);
read_sysreg!(pmceid2: (p15, 0, c14, c9, 4), u32: crate::registers::Pmceid2, safe, crate::fake::SYSREGS);
read_sysreg!(pmceid3: (p15, 0, c14, c9, 5), u32: crate::registers::Pmceid3, safe, crate::fake::SYSREGS);
read_write_sysreg!(pmcntenclr: (p15, 0, c12, c9, 2), u32: crate::registers::Pmcntenclr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmcntenset: (p15, 0, c12, c9, 1), u32: crate::registers::Pmcntenset, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmcr: (p15, 0, c12, c9, 0), u32: crate::registers::Pmcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmintenclr: (p15, 0, c14, c9, 2), u32: crate::registers::Pmintenclr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmintenset: (p15, 0, c14, c9, 1), u32: crate::registers::Pmintenset, safe_read, crate::fake::SYSREGS);
read_sysreg!(pmmir: (p15, 0, c14, c9, 6), u32: crate::registers::Pmmir, safe, crate::fake::SYSREGS);
read_write_sysreg!(pmovsr: (p15, 0, c12, c9, 3), u32: crate::registers::Pmovsr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmovsset: (p15, 0, c14, c9, 3), u32: crate::registers::Pmovsset, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmselr: (p15, 0, c12, c9, 5), u32: crate::registers::Pmselr, safe_read, crate::fake::SYSREGS);
write_sysreg!(pmswinc: (p15, 0, c12, c9, 4), u32: crate::registers::Pmswinc, crate::fake::SYSREGS);
read_write_sysreg!(pmuserenr: (p15, 0, c14, c9, 0), u32: crate::registers::Pmuserenr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(pmxevtyper: (p15, 0, c13, c9, 1), u32: crate::registers::Pmxevtyper, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(prrr: (p15, 0, c2, c10, 0), u32: crate::registers::Prrr, safe_read, crate::fake::SYSREGS);
read_sysreg!(revidr: (p15, 0, c0, c0, 6), u32, safe, crate::fake::SYSREGS);
read_write_sysreg!(rmr: (p15, 0, c0, c12, 2), u32: crate::registers::Rmr, safe_read, crate::fake::SYSREGS);
read_sysreg!(rvbar: (p15, 0, c0, c12, 1), u32: crate::registers::Rvbar, safe, crate::fake::SYSREGS);
read_write_sysreg!(scr: (p15, 0, c1, c1, 0), u32: crate::registers::Scr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(sctlr: (p15, 0, c0, c1, 0), u32: crate::registers::Sctlr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(sdcr: (p15, 0, c3, c1, 1), u32: crate::registers::Sdcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(sder: (p15, 0, c1, c1, 1), u32: crate::registers::Sder, safe_read, crate::fake::SYSREGS);
read_sysreg!(tcmtr: (p15, 0, c0, c0, 2), u32, safe, crate::fake::SYSREGS);
read_sysreg!(tlbtr: (p15, 0, c0, c0, 3), u32: crate::registers::Tlbtr, safe, crate::fake::SYSREGS);
read_write_sysreg!(tpidrprw: (p15, 0, c0, c13, 4), u32: crate::registers::Tpidrprw, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(tpidruro: (p15, 0, c0, c13, 3), u32: crate::registers::Tpidruro, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(tpidrurw: (p15, 0, c0, c13, 2), u32: crate::registers::Tpidrurw, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(trfcr: (p15, 0, c2, c1, 1), u32: crate::registers::Trfcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(ttbcr: (p15, 0, c0, c2, 2), u32: crate::registers::Ttbcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(ttbcr2: (p15, 0, c0, c2, 3), u32: crate::registers::Ttbcr2, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(ttbr0: (p15, 0, c2), u64: crate::registers::Ttbr0, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(ttbr1: (p15, 1, c2), u64: crate::registers::Ttbr1, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vbar: (p15, 0, c0, c12, 0), u32: crate::registers::Vbar, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vdfsr: (p15, 4, c2, c5, 3), u32: crate::registers::Vdfsr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vdisr: (p15, 0, c1, c12, 1), u32: crate::registers::Vdisr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vmpidr: (p15, 0, c0, c0, 5), u32: crate::registers::Vmpidr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vpidr: (p15, 0, c0, c0, 0), u32: crate::registers::Vpidr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vtcr: (p15, 4, c1, c2, 2), u32: crate::registers::Vtcr, safe_read, crate::fake::SYSREGS);
read_write_sysreg!(vttbr: (p15, 6, c2), u64: crate::registers::Vttbr, safe_read, crate::fake::SYSREGS);
